# Generated by Django 3.1.7 on 2021-05-08 00:56

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('produto', models.CharField(max_length=200)),
                ('observacao', models.TextField(max_length=200)),
                ('categoria', models.CharField(choices=[('Saúde', 'Saúde'), ('Lazer', 'Lazer'), ('Gasto Fixo', 'Gasto Fixo'), ('Gasto Não previsto', 'Gasto Não previsto'), ('Financiamento', 'Financiamento'), ('Alimentação', 'Alimentação'), ('Financiamento', 'Financiamento'), ('Educação', 'Educação'), ('Imposto', 'Imposto'), ('Investimento', 'Investimento')], max_length=30)),
                ('tipo', models.CharField(choices=[('Boleto', 'Boleto'), ('Crédito', 'Crédito'), ('Empréstimo', 'Empréstimo')], max_length=20)),
                ('status', models.CharField(choices=[('Pago', 'Pago'), ('Não Pago', 'Não Pago')], default='-', max_length=10)),
                ('parcelas', models.CharField(choices=[('0', 'ROTATIVO'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='-', max_length=10)),
                ('vencimento', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('credor', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hrs_trab_pagar', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
